### ISSUE TITLE
Coupon Ordering Feature

### ISSUE THREAD

**Issue by Rkrahul005** [dailykit/HERN#686]
Hello Team,

We have a request from a client for the ordering of coupons.
They want a feature to arrange the coupon as per requirement.
If I have a total of 6 coupons so we should have the option to arrange the coupon as per requirement.
Please look into it.
If you need any clarification, feel free to contact me.

**Comment by futuregridtechnologies** [comment]
Hmm.. good enhancement

Will take it up in next sprint.

Steps to do:

1. Add a position column in brand_coupon table
2. Wrap the brand coupon link module in our drag and drop module
3. On store side, add order by position desc in the coupon query.

@shubhamz950

**Comment by ng11tk** [comment]
re: steps to do @futuregridtechnologies @shubhamz950 @rahul72925 @rahul72925 

1. we do not have the direct table in ui from brand_coupon
2. So that we can not provide the drag n drop in this table
3. if we use the brand context to display coupons in coupon table than we can use the brand_coupon table for brand id but in this case how we will manage the location fields as if a specific conditions is for a location
