### ISSUE TITLE
Store Profile Wallet : Wallet page shows error in new version

### ISSUE THREAD

**Issue by shubhamz950** [dailykit/HERN#882]
**Describe the bug**
Wallet page is not working on store

**To Reproduce**
1. Go to Store and login
2. Click on profile and go to wallet

**Expected behavior**
Wallet should be working or if it's not active from admin side, it should show some info as "coming soon" or wallet option from profile navbar should be hidden.

**Screenshots**
<img width="1440" alt="Screenshot 2022-04-29 at 12 12 05" src="https://user-images.githubusercontent.com/84710678/165896510-8d355093-ab41-4a8b-aaf6-3a8424ab7097.png">
<img width="1440" alt="Screenshot 2022-04-29 at 12 15 15" src="https://user-images.githubusercontent.com/84710678/165896523-39c1a28f-6e2d-4685-aebf-864dc621266c.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by chiragsoni81245** [comment]
Hey, @shubhamz950 
Its coming because we have different `identifier` for Wallet brand-setting in `testhern` and in `breezychef`

![Screenshot 2022-05-01 035832](https://user-images.githubusercontent.com/52407451/166124683-a0a8ac7e-e154-45ff-adfe-223896ffca62.jpg)
![Screenshot 2022-05-01 035759](https://user-images.githubusercontent.com/52407451/166124686-71375007-c41c-465d-8f6b-0fac4d537a4a.jpg)

*these Identifiers should be same for all of our clients.*

**Comment by shubhamz950** [comment]
@chiragsoni81245 yeah, we should use `Wallet` for this identifier
